"""Models for the Orion script agent."""

from dataclasses import dataclass


@dataclass
class ScriptSection:
    """A section of a generated video script."""

    title: str
    content: str


@dataclass
class VideoScript:
    """Structured video script generated from company intelligence."""

    title: str
    hook: str
    sections: list[ScriptSection]
    call_to_action: str
    summary: str
    generated_by: str

    def to_markdown(self) -> str:
        """Return the script as Markdown."""
        section_blocks = "\n\n".join(
            f"## {section.title}\n\n{section.content}" for section in self.sections
        )
        return (
            f"# {self.title}\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Hook\n\n{self.hook}\n\n"
            f"{section_blocks}\n\n"
            f"## Call To Action\n\n{self.call_to_action}\n\n"
            f"## Summary\n\n{self.summary}"
        )
