"""Models for the Lumen storyboard agent."""

from dataclasses import dataclass, field


@dataclass
class StoryboardScene:
    """A single scene in a short-form video storyboard."""

    scene_number: int
    duration_seconds: float
    narration: str
    visual_description: str
    camera_direction: str
    on_screen_text: str | None
    transition: str

    def __post_init__(self) -> None:
        """Validate scene values."""
        if self.scene_number <= 0:
            msg = "scene_number must be greater than 0."
            raise ValueError(msg)

        if self.duration_seconds <= 0:
            msg = "duration_seconds must be greater than 0."
            raise ValueError(msg)

        required_fields = {
            "narration": self.narration,
            "visual_description": self.visual_description,
            "camera_direction": self.camera_direction,
            "transition": self.transition,
        }
        for field_name, value in required_fields.items():
            if not value.strip():
                msg = f"{field_name} must not be empty."
                raise ValueError(msg)


@dataclass
class Storyboard:
    """Structured storyboard generated from a script and optimized hook."""

    title: str
    selected_hook: str
    scenes: list[StoryboardScene]
    visual_style: str
    summary: str
    generated_by: str
    total_duration_seconds: float = field(init=False)

    def __post_init__(self) -> None:
        """Validate storyboard values and calculate duration."""
        if len(self.scenes) < 3:
            msg = "storyboard must contain at least 3 scenes."
            raise ValueError(msg)

        self.total_duration_seconds = sum(
            scene.duration_seconds for scene in self.scenes
        )

    def to_markdown(self) -> str:
        """Return the storyboard as Markdown."""
        scene_blocks = "\n\n".join(
            (
                f"## Scene {scene.scene_number}\n\n"
                f"- Duration: {scene.duration_seconds}s\n"
                f"- Narration: {scene.narration}\n"
                f"- Visual: {scene.visual_description}\n"
                f"- Camera: {scene.camera_direction}\n"
                f"- Text: {scene.on_screen_text or ''}\n"
                f"- Transition: {scene.transition}"
            )
            for scene in self.scenes
        )
        return (
            f"# {self.title}\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"Selected Hook: {self.selected_hook}\n\n"
            f"Visual Style: {self.visual_style}\n\n"
            f"Total Duration: {self.total_duration_seconds}s\n\n"
            f"{scene_blocks}\n\n"
            f"## Summary\n\n{self.summary}"
        )
