"""Trend research report model."""

from dataclasses import dataclass

from agents.trend_research.models import TrendResult


@dataclass
class TrendReport:
    """Structured trend research report generated by Atlas."""

    query: str
    summary: str
    trends: list[TrendResult]
    generated_by: str

    def to_markdown(self) -> str:
        """Return the report as Markdown."""
        trend_sections = "\n\n".join(
            (
                f"### {trend.topic}\n\n"
                f"- Score: {trend.score}\n"
                f"- Source: {trend.source}\n"
                f"- Reason: {trend.reason}"
            )
            for trend in self.trends
        )
        return (
            f"# Trend Report: {self.query}\n\n"
            f"Generated by: {self.generated_by}\n\n"
            "## Summary\n\n"
            f"{self.summary}\n\n"
            "## Trends\n\n"
            f"{trend_sections}"
        )
