"""Models for the Helios CEO agent."""

from dataclasses import dataclass, field
from datetime import UTC, datetime


@dataclass
class CompanyPriority:
    """A company priority proposed by the CEO agent."""

    title: str
    reason: str
    priority_score: float

    def __post_init__(self) -> None:
        """Validate company priority values."""
        if not 0.0 <= self.priority_score <= 1.0:
            msg = "priority_score must be between 0.0 and 1.0."
            raise ValueError(msg)


@dataclass
class ExecutiveDecision:
    """A strategic decision proposed by the CEO agent."""

    title: str
    rationale: str
    expected_impact: str
    confidence: float

    def __post_init__(self) -> None:
        """Validate executive decision values."""
        if not 0.0 <= self.confidence <= 1.0:
            msg = "confidence must be between 0.0 and 1.0."
            raise ValueError(msg)


@dataclass
class ExecutiveDecisionReport:
    """Structured CEO decision report."""

    company_status: str
    priorities: list[CompanyPriority]
    decisions: list[ExecutiveDecision]
    executive_summary: str
    generated_by: str
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def __post_init__(self) -> None:
        """Validate executive decision report values."""
        if not self.priorities:
            msg = "priorities must contain at least one CompanyPriority."
            raise ValueError(msg)

        if not self.decisions:
            msg = "decisions must contain at least one ExecutiveDecision."
            raise ValueError(msg)

    def to_markdown(self) -> str:
        """Return the executive decision report as Markdown."""
        priorities = "\n".join(
            (
                f"- {priority.title}: {priority.priority_score} "
                f"({priority.reason})"
            )
            for priority in self.priorities
        )
        decisions = "\n".join(
            (
                f"- {decision.title}: {decision.expected_impact} "
                f"(confidence: {decision.confidence})"
            )
            for decision in self.decisions
        )
        return (
            "# Executive Decision Report\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"Company Status: {self.company_status}\n\n"
            f"## Executive Summary\n\n{self.executive_summary}\n\n"
            f"## Priorities\n\n{priorities}\n\n"
            f"## Decisions\n\n{decisions}"
        )
