"""Models for the Insight analytics agent."""

from dataclasses import dataclass, field
from datetime import UTC, datetime


@dataclass
class PlatformMetrics:
    """Platform-level content performance metrics."""

    platform: str
    views: int
    watch_time_seconds: float
    average_watch_percentage: float
    likes: int
    comments: int
    shares: int
    saves: int
    followers_gained: int
    ctr: float
    engagement_rate: float

    def __post_init__(self) -> None:
        """Validate metric values."""
        if not self.platform.strip():
            msg = "platform must not be empty."
            raise ValueError(msg)

        numeric_values = {
            "views": self.views,
            "watch_time_seconds": self.watch_time_seconds,
            "average_watch_percentage": self.average_watch_percentage,
            "likes": self.likes,
            "comments": self.comments,
            "shares": self.shares,
            "saves": self.saves,
            "followers_gained": self.followers_gained,
            "ctr": self.ctr,
            "engagement_rate": self.engagement_rate,
        }
        for field_name, value in numeric_values.items():
            if value < 0:
                msg = f"{field_name} must be greater than or equal to 0."
                raise ValueError(msg)

        if not 0 <= self.average_watch_percentage <= 100:
            msg = "average_watch_percentage must be between 0 and 100."
            raise ValueError(msg)

    @property
    def engagement_total(self) -> int:
        """Return total engagement actions for this platform."""
        return self.likes + self.comments + self.shares + self.saves


@dataclass
class AnalyticsReport:
    """Platform-independent analytics report for published content."""

    report_id: str
    video_id: str
    metrics: list[PlatformMetrics]
    total_views: int
    total_engagement: int
    strongest_platform: str
    weakest_platform: str
    summary: str
    generated_by: str
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def __post_init__(self) -> None:
        """Validate report values."""
        if not self.metrics:
            msg = "metrics must contain at least one PlatformMetrics item."
            raise ValueError(msg)

    def to_markdown(self) -> str:
        """Return the analytics report as Markdown."""
        metric_lines = "\n".join(
            (
                f"- {metric.platform}: {metric.views} views, "
                f"{metric.engagement_total} engagements, "
                f"{metric.average_watch_percentage}% avg watch"
            )
            for metric in self.metrics
        )
        return (
            f"# Analytics Report: {self.video_id}\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"Report ID: {self.report_id}\n\n"
            f"Total Views: {self.total_views}\n\n"
            f"Total Engagement: {self.total_engagement}\n\n"
            f"Strongest Platform: {self.strongest_platform}\n\n"
            f"Weakest Platform: {self.weakest_platform}\n\n"
            f"## Platform Metrics\n\n{metric_lines}\n\n"
            f"## Summary\n\n{self.summary}"
        )
