"""Agent capability definitions."""

from enum import StrEnum


class AgentCapability(StrEnum):
    """Capabilities an agent can declare support for."""

    CEO = "CEO"
    TREND_RESEARCH = "TREND_RESEARCH"
    AUDIENCE_RESEARCH = "AUDIENCE_RESEARCH"
    STRATEGY = "STRATEGY"
    KNOWLEDGE = "KNOWLEDGE"
    SCRIPT = "SCRIPT"
    HOOK = "HOOK"
    SCRIPT_WRITING = "SCRIPT_WRITING"
    STORYBOARD = "STORYBOARD"
    CREATIVE_DIRECTION = "CREATIVE_DIRECTION"
    AVATAR = "AVATAR"
    VOICE = "VOICE"
    MUSIC = "MUSIC"
    VIDEO_PRODUCTION = "VIDEO_PRODUCTION"
    THUMBNAIL = "THUMBNAIL"
    CAPTION = "CAPTION"
    PUBLISHING = "PUBLISHING"
    ANALYTICS = "ANALYTICS"
    BUSINESS_INTELLIGENCE = "BUSINESS_INTELLIGENCE"
    LEARNING = "LEARNING"
    PREDICTION = "PREDICTION"
    MEMORY = "MEMORY"
    QUALITY_CONTROL = "QUALITY_CONTROL"
