"""Helios company blueprint definitions."""

from engine.company.agent_definition import AgentDefinition
from engine.company.department import Department
from engine.runtime.capability import AgentCapability


HELIOS_COMPANY_BLUEPRINT: tuple[AgentDefinition, ...] = (
    AgentDefinition(
        agent_id="ceo",
        display_name="CEO",
        department=Department.EXECUTIVE,
        capability="EXECUTIVE_LEADERSHIP",
        description="Sets company direction and resolves strategic trade-offs.",
        responsibilities=("Define company priorities", "Approve operating principles"),
        inputs=("company goals", "performance reports"),
        outputs=("strategic decisions", "priority guidance"),
        required_tools=("planning_tool", "reporting_tool"),
        memory_access=("strategy", "reports"),
        event_subscriptions=("report.ready", "alert.raised"),
    ),
    AgentDefinition(
        agent_id="system_supervisor",
        display_name="System Supervisor",
        department=Department.OPERATIONS,
        capability="SYSTEM_SUPERVISION",
        description="Monitors operational state and coordinates system services.",
        responsibilities=("Inspect runtime health", "Coordinate operational responses"),
        inputs=("runtime events", "health snapshots"),
        outputs=("supervision notes", "operational actions"),
        required_tools=("runtime_inspection_tool", "event_tool"),
        memory_access=("operations",),
        event_subscriptions=("runtime.started", "runtime.stopped", "task.failed"),
    ),
    AgentDefinition(
        agent_id="trend_research",
        display_name="Trend Research",
        department=Department.RESEARCH,
        capability="TREND_RESEARCH",
        description="Identifies trend candidates and supporting evidence.",
        responsibilities=("Research topic demand", "Rank trend opportunities"),
        inputs=("research brief", "query"),
        outputs=("trend candidates", "trend report input"),
        required_tools=("trend_research_tool", "llm"),
        memory_access=("trend_reports",),
        event_subscriptions=("task.created",),
    ),
    AgentDefinition(
        agent_id="audience_research",
        display_name="Audience Research",
        department=Department.RESEARCH,
        capability="AUDIENCE_RESEARCH",
        description="Maps audience segments, pains, motivations and language.",
        responsibilities=("Identify audience segments", "Summarize audience needs"),
        inputs=("topic", "market notes"),
        outputs=("audience profile", "message insights"),
        required_tools=("research_tool", "llm"),
        memory_access=("audience_profiles",),
        event_subscriptions=("trend.reported",),
    ),
    AgentDefinition(
        agent_id="strategy",
        display_name="Strategy",
        department=Department.STRATEGY,
        capability="STRATEGY",
        description="Turns research into content positioning and sequencing decisions.",
        responsibilities=("Choose content angles", "Prioritize content opportunities"),
        inputs=("trend report", "audience profile"),
        outputs=("content strategy", "angle brief"),
        required_tools=("planning_tool", "llm"),
        memory_access=("strategies", "trend_reports", "audience_profiles"),
        event_subscriptions=("trend.reported", "audience.profiled"),
    ),
    AgentDefinition(
        agent_id="knowledge",
        display_name="Knowledge",
        department=Department.KNOWLEDGE,
        capability="KNOWLEDGE_MANAGEMENT",
        description="Maintains reusable company knowledge and operating context.",
        responsibilities=("Organize knowledge assets", "Prepare context for agents"),
        inputs=("memory entries", "research outputs"),
        outputs=("knowledge notes", "context bundles"),
        required_tools=("memory_tool", "summarization_tool"),
        memory_access=("company_knowledge",),
        event_subscriptions=("memory.saved",),
    ),
    AgentDefinition(
        agent_id="script",
        display_name="Script",
        department=Department.WRITING,
        capability="SCRIPT_WRITING",
        description="Drafts structured scripts from strategy and research context.",
        responsibilities=("Write scripts", "Adapt scripts to target formats"),
        inputs=("angle brief", "audience profile"),
        outputs=("script draft", "script outline"),
        required_tools=("llm", "style_guide_tool"),
        memory_access=("scripts", "style_guides"),
        event_subscriptions=("strategy.approved",),
    ),
    AgentDefinition(
        agent_id="hook",
        display_name="Hook",
        department=Department.WRITING,
        capability="HOOK_WRITING",
        description="Creates opening hooks and retention patterns for scripts.",
        responsibilities=("Draft hooks", "Improve retention openings"),
        inputs=("script outline", "audience pain"),
        outputs=("hook options", "retention notes"),
        required_tools=("llm", "copy_tool"),
        memory_access=("hooks", "scripts"),
        event_subscriptions=("script.drafted",),
    ),
    AgentDefinition(
        agent_id="storyboard",
        display_name="Storyboard",
        department=Department.CREATIVE,
        capability="STORYBOARD",
        description="Converts scripts into scene plans and visual beats.",
        responsibilities=("Plan scenes", "Map visuals to script sections"),
        inputs=("script draft", "creative direction"),
        outputs=("storyboard", "shot list"),
        required_tools=("storyboard_tool", "llm"),
        memory_access=("storyboards", "scripts"),
        event_subscriptions=("script.approved",),
    ),
    AgentDefinition(
        agent_id="creative_director",
        display_name="Creative Director",
        department=Department.CREATIVE,
        capability="CREATIVE_DIRECTION",
        description="Defines creative standards and reviews visual consistency.",
        responsibilities=("Set creative direction", "Review creative outputs"),
        inputs=("brand notes", "storyboard"),
        outputs=("creative brief", "review notes"),
        required_tools=("review_tool", "asset_tool"),
        memory_access=("creative_briefs", "brand_guidelines"),
        event_subscriptions=("storyboard.ready",),
    ),
    AgentDefinition(
        agent_id="avatar",
        display_name="Avatar",
        department=Department.PRODUCTION,
        capability="AVATAR_PRODUCTION",
        description="Prepares avatar-related production requirements and outputs.",
        responsibilities=("Prepare avatar plan", "Coordinate avatar assets"),
        inputs=("script", "creative brief"),
        outputs=("avatar production brief", "avatar asset list"),
        required_tools=("avatar_tool", "asset_tool"),
        memory_access=("production_assets",),
        event_subscriptions=("creative.approved",),
    ),
    AgentDefinition(
        agent_id="video_production",
        display_name="Video Production",
        department=Department.PRODUCTION,
        capability="VIDEO_PRODUCTION",
        description="Assembles video production plans and render-ready assets.",
        responsibilities=("Coordinate video assembly", "Prepare render inputs"),
        inputs=("storyboard", "asset list"),
        outputs=("video production package", "render checklist"),
        required_tools=("video_tool", "asset_tool"),
        memory_access=("production_assets", "storyboards"),
        event_subscriptions=("storyboard.ready", "voice.ready"),
    ),
    AgentDefinition(
        agent_id="voice",
        display_name="Voice",
        department=Department.PRODUCTION,
        capability="VOICE_PRODUCTION",
        description="Plans narration, voice direction and audio delivery requirements.",
        responsibilities=("Prepare voice brief", "Coordinate narration assets"),
        inputs=("script", "tone guidance"),
        outputs=("voice brief", "narration asset list"),
        required_tools=("voice_tool", "audio_tool"),
        memory_access=("voice_assets", "scripts"),
        event_subscriptions=("script.approved",),
    ),
    AgentDefinition(
        agent_id="music_sound",
        display_name="Music & Sound",
        department=Department.PRODUCTION,
        capability="MUSIC_SOUND",
        description="Plans music, sound design and audio atmosphere for content.",
        responsibilities=("Select sound direction", "Prepare sound requirements"),
        inputs=("creative brief", "storyboard"),
        outputs=("sound brief", "music notes"),
        required_tools=("audio_tool", "asset_tool"),
        memory_access=("sound_assets", "creative_briefs"),
        event_subscriptions=("creative.approved",),
    ),
    AgentDefinition(
        agent_id="thumbnail",
        display_name="Thumbnail",
        department=Department.CREATIVE,
        capability="THUMBNAIL",
        description="Creates thumbnail concepts and packaging guidance.",
        responsibilities=("Draft thumbnail concepts", "Align thumbnails with angle"),
        inputs=("strategy brief", "creative brief"),
        outputs=("thumbnail brief", "thumbnail variants"),
        required_tools=("image_tool", "copy_tool"),
        memory_access=("thumbnail_assets", "creative_briefs"),
        event_subscriptions=("video.package.ready",),
    ),
    AgentDefinition(
        agent_id="caption",
        display_name="Caption",
        department=Department.DISTRIBUTION,
        capability="CAPTION",
        description="Creates captions and supporting distribution copy.",
        responsibilities=("Write captions", "Adapt copy by channel"),
        inputs=("script", "platform plan"),
        outputs=("caption variants", "post copy"),
        required_tools=("copy_tool", "llm"),
        memory_access=("distribution_copy", "scripts"),
        event_subscriptions=("video.package.ready",),
    ),
    AgentDefinition(
        agent_id="publishing",
        display_name="Publishing",
        department=Department.DISTRIBUTION,
        capability="PUBLISHING",
        description="Prepares platform-specific publishing payloads and schedules.",
        responsibilities=("Prepare publishing package", "Coordinate release timing"),
        inputs=("video package", "caption variants"),
        outputs=("publishing plan", "platform payload"),
        required_tools=("publishing_tool", "calendar_tool"),
        memory_access=("publishing_plans", "distribution_copy"),
        event_subscriptions=("content.quality.approved",),
    ),
    AgentDefinition(
        agent_id="analytics",
        display_name="Analytics",
        department=Department.ANALYTICS,
        capability="ANALYTICS",
        description="Analyzes performance data and summarizes content outcomes.",
        responsibilities=("Measure performance", "Find content patterns"),
        inputs=("platform metrics", "publishing records"),
        outputs=("analytics report", "performance insights"),
        required_tools=("analytics_tool", "reporting_tool"),
        memory_access=("analytics_reports", "publishing_plans"),
        event_subscriptions=("content.published",),
    ),
    AgentDefinition(
        agent_id="business_intelligence",
        display_name="Business Intelligence",
        department=Department.ANALYTICS,
        capability=AgentCapability.BUSINESS_INTELLIGENCE.value,
        description="Analyzes portfolio performance across brands and channels.",
        responsibilities=(
            "markenuebergreifende Performance analysieren",
            "Wachstum, Kosten und Profitabilitaet vergleichen",
            "Ressourcenallokation empfehlen",
            "schwache Marken oder Kanaele identifizieren",
            "Managementberichte fuer den CEO vorbereiten",
        ),
        inputs=(
            "Analytics-Daten",
            "Kosten-Daten",
            "Learning-Erkenntnisse",
            "Prediction-Ergebnisse",
        ),
        outputs=(
            "Portfolio-Auswertung",
            "Ressourcenempfehlungen",
            "Profitabilitaetsbericht",
            "Management Summary",
        ),
        required_tools=("analytics_tool", "cost_tool", "reporting_tool"),
        memory_access=("analytics_reports", "cost_reports", "learning_notes", "predictions"),
        event_subscriptions=("analytics.reported", "learning.created", "prediction.created"),
    ),
    AgentDefinition(
        agent_id="learning",
        display_name="Learning",
        department=Department.OPTIMIZATION,
        capability="LEARNING",
        description="Turns analytics outcomes into reusable operating lessons.",
        responsibilities=("Extract learnings", "Update improvement guidance"),
        inputs=("analytics report", "experiment results"),
        outputs=("learning notes", "optimization guidance"),
        required_tools=("analysis_tool", "memory_tool"),
        memory_access=("learning_notes", "analytics_reports"),
        event_subscriptions=("analytics.reported",),
    ),
    AgentDefinition(
        agent_id="memory",
        display_name="Memory",
        department=Department.MEMORY,
        capability="MEMORY",
        description="Stores and retrieves durable company knowledge.",
        responsibilities=("Persist important artifacts", "Provide memory context"),
        inputs=("reports", "decisions", "artifacts"),
        outputs=("memory entries", "retrieved context"),
        required_tools=("memory_tool",),
        memory_access=("company_memory",),
        event_subscriptions=("memory.save.requested",),
    ),
    AgentDefinition(
        agent_id="experiment",
        display_name="Experiment",
        department=Department.OPTIMIZATION,
        capability="EXPERIMENT",
        description="Designs controlled content experiments and success criteria.",
        responsibilities=("Design experiments", "Track experiment hypotheses"),
        inputs=("strategy brief", "analytics insights"),
        outputs=("experiment plan", "success metrics"),
        required_tools=("planning_tool", "analytics_tool"),
        memory_access=("experiments", "analytics_reports"),
        event_subscriptions=("learning.created",),
    ),
    AgentDefinition(
        agent_id="report",
        display_name="Report",
        department=Department.ANALYTICS,
        capability="REPORTING",
        description="Creates structured reports for company visibility and decisions.",
        responsibilities=("Compile reports", "Summarize operational state"),
        inputs=("analytics insights", "runtime events"),
        outputs=("company report", "status summary"),
        required_tools=("reporting_tool", "llm"),
        memory_access=("reports", "analytics_reports"),
        event_subscriptions=("analytics.reported", "task.failed"),
    ),
    AgentDefinition(
        agent_id="alert",
        display_name="Alert",
        department=Department.OPERATIONS,
        capability="ALERTING",
        description="Raises operational alerts for failures, risks and thresholds.",
        responsibilities=("Detect alert conditions", "Notify relevant departments"),
        inputs=("runtime events", "cost signals"),
        outputs=("alert notice", "incident summary"),
        required_tools=("event_tool", "notification_tool"),
        memory_access=("alerts", "operations"),
        event_subscriptions=("task.failed", "cost.threshold.reached"),
    ),
    AgentDefinition(
        agent_id="compliance",
        display_name="Compliance",
        department=Department.COMPLIANCE,
        capability="COMPLIANCE",
        description="Checks content and operations against compliance rules.",
        responsibilities=("Review compliance risks", "Approve or reject packages"),
        inputs=("content package", "policy guidance"),
        outputs=("compliance review", "risk notes"),
        required_tools=("policy_tool", "review_tool"),
        memory_access=("compliance_reviews", "policy_guidance"),
        event_subscriptions=("content.ready.for.review",),
    ),
    AgentDefinition(
        agent_id="cost_manager",
        display_name="Cost Manager",
        department=Department.OPERATIONS,
        capability="COST_MANAGEMENT",
        description="Tracks cost signals and keeps provider usage within budgets.",
        responsibilities=("Monitor cost signals", "Recommend budget controls"),
        inputs=("usage records", "provider metadata"),
        outputs=("cost report", "budget alert"),
        required_tools=("cost_tool", "reporting_tool"),
        memory_access=("cost_reports", "operations"),
        event_subscriptions=("provider.usage.recorded",),
    ),
    AgentDefinition(
        agent_id="prompt_engineer",
        display_name="Prompt Engineer",
        department=Department.OPTIMIZATION,
        capability="PROMPT_ENGINEERING",
        description="Improves prompt templates and instruction quality.",
        responsibilities=("Maintain prompt templates", "Optimize prompt performance"),
        inputs=("agent feedback", "quality reports"),
        outputs=("prompt revision", "prompt guidance"),
        required_tools=("prompt_tool", "evaluation_tool"),
        memory_access=("prompt_library", "quality_reports"),
        event_subscriptions=("quality.reported",),
    ),
    AgentDefinition(
        agent_id="collaboration",
        display_name="Collaboration",
        department=Department.OPERATIONS,
        capability="COLLABORATION",
        description="Coordinates handoffs between departments through tasks and events.",
        responsibilities=("Coordinate handoffs", "Track dependencies"),
        inputs=("task events", "department requests"),
        outputs=("handoff plan", "dependency notes"),
        required_tools=("task_tool", "event_tool"),
        memory_access=("operations", "handoffs"),
        event_subscriptions=("task.created", "task.dispatched", "task.failed"),
    ),
    AgentDefinition(
        agent_id="content_quality",
        display_name="Content Quality",
        department=Department.COMPLIANCE,
        capability="QUALITY_CONTROL",
        description="Reviews content quality before distribution.",
        responsibilities=("Check clarity and completeness", "Review brand quality"),
        inputs=("content package", "quality checklist"),
        outputs=("quality review", "approval notes"),
        required_tools=("quality_tool", "review_tool"),
        memory_access=("quality_reports", "content_packages"),
        event_subscriptions=("content.package.ready",),
    ),
    AgentDefinition(
        agent_id="memory_optimizer",
        display_name="Memory Optimizer",
        department=Department.MEMORY,
        capability="MEMORY_OPTIMIZATION",
        description="Keeps memory useful by improving structure and reducing duplication.",
        responsibilities=("Review memory quality", "Suggest memory consolidation"),
        inputs=("memory entries", "usage patterns"),
        outputs=("memory optimization plan", "cleanup recommendations"),
        required_tools=("memory_tool", "analysis_tool"),
        memory_access=("company_memory", "memory_quality"),
        event_subscriptions=("memory.saved",),
    ),
    AgentDefinition(
        agent_id="prediction",
        display_name="Prediction",
        department=Department.ANALYTICS,
        capability="PREDICTION",
        description="Forecasts likely content outcomes from research and history.",
        responsibilities=("Estimate content potential", "Compare predicted outcomes"),
        inputs=("trend report", "analytics history"),
        outputs=("prediction report", "confidence notes"),
        required_tools=("analytics_tool", "forecast_tool"),
        memory_access=("predictions", "analytics_reports"),
        event_subscriptions=("strategy.created", "analytics.reported"),
    ),
)
