"""Models for the Echo avatar agent."""

from dataclasses import dataclass


@dataclass
class AvatarProfile:
    """Structured avatar profile for video production."""

    name: str
    age_group: str
    appearance: str
    clothing_style: str
    hairstyle: str
    facial_expression: str
    body_language: str
    voice_style: str
    energy_level: str
    platform_fit: str
    branding_notes: str
    summary: str
    generated_by: str

    def to_markdown(self) -> str:
        """Return the avatar profile as Markdown."""
        return (
            f"# Avatar Profile: {self.name}\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Age Group\n\n{self.age_group}\n\n"
            f"## Appearance\n\n{self.appearance}\n\n"
            f"## Clothing Style\n\n{self.clothing_style}\n\n"
            f"## Hairstyle\n\n{self.hairstyle}\n\n"
            f"## Facial Expression\n\n{self.facial_expression}\n\n"
            f"## Body Language\n\n{self.body_language}\n\n"
            f"## Voice Style\n\n{self.voice_style}\n\n"
            f"## Energy Level\n\n{self.energy_level}\n\n"
            f"## Platform Fit\n\n{self.platform_fit}\n\n"
            f"## Branding Notes\n\n{self.branding_notes}\n\n"
            f"## Summary\n\n{self.summary}"
        )
