"""Immutable models for deterministic ARGUS health reports."""

from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum, StrEnum
import json
import re
from types import MappingProxyType
from typing import Any, cast

_SENSITIVE_KEYS = {
    "api_key",
    "apikey",
    "authorization",
    "password",
    "secret",
    "token",
}
_SENSITIVE_TEXT_PATTERN = re.compile(
    r"(?i)(api[_-]?key|authorization|password|secret|token)\s*[:=]\s*[^\s,;]+",
)
_REDACTED = "[REDACTED]"


class GuardianStatus(StrEnum):
    """Overall ARGUS system states."""

    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"


class CheckStatus(StrEnum):
    """Possible outcomes for one guardian check."""

    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    SKIPPED = "SKIPPED"


class Severity(StrEnum):
    """Operational impact levels assigned to guardian checks."""

    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass(frozen=True, kw_only=True)
class SystemCheckResult:
    """Immutable and secret-safe result from one system check."""

    id: str
    name: str
    severity: Severity
    status: CheckStatus
    summary: str
    details: Mapping[str, Any] = field(default_factory=dict)
    checked_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    duration_seconds: float = 0.0

    def __post_init__(self) -> None:
        """Validate fields and protect details from external mutation."""
        for field_name, value in (
            ("id", self.id),
            ("name", self.name),
            ("summary", self.summary),
        ):
            if not value.strip():
                msg = f"{field_name} must not be empty."
                raise ValueError(msg)
        if self.checked_at.tzinfo is not UTC:
            msg = "checked_at must use UTC."
            raise ValueError(msg)
        if self.duration_seconds < 0:
            msg = "duration_seconds must not be negative."
            raise ValueError(msg)
        if not isinstance(self.details, Mapping):
            msg = "details must be a mapping."
            raise ValueError(msg)

        object.__setattr__(self, "summary", _redact_text(self.summary))
        object.__setattr__(self, "details", _protect_mapping(self.details))


@dataclass(frozen=True, kw_only=True)
class SystemHealthReport:
    """Complete immutable system health report generated by ARGUS."""

    guardian_version: str
    overall_status: GuardianStatus
    checks: tuple[SystemCheckResult, ...]
    counters: Mapping[CheckStatus, int]
    summary: str
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    generated_by: str = "Argus"

    def __post_init__(self) -> None:
        """Validate report integrity and protect counter state."""
        if not self.guardian_version.strip():
            msg = "guardian_version must not be empty."
            raise ValueError(msg)
        if not self.summary.strip():
            msg = "summary must not be empty."
            raise ValueError(msg)
        if not self.generated_by.strip():
            msg = "generated_by must not be empty."
            raise ValueError(msg)
        if self.created_at.tzinfo is not UTC:
            msg = "created_at must use UTC."
            raise ValueError(msg)
        if not isinstance(self.checks, tuple):
            object.__setattr__(self, "checks", tuple(self.checks))
        if not isinstance(self.counters, Mapping):
            msg = "counters must be a mapping."
            raise ValueError(msg)
        protected_counters = MappingProxyType(dict(self.counters))
        object.__setattr__(
            self,
            "counters",
            cast(Mapping[CheckStatus, int], protected_counters),
        )
        object.__setattr__(self, "summary", _redact_text(self.summary))

    def to_markdown(self) -> str:
        """Return a readable Markdown representation of the report."""
        check_lines = "\n".join(
            f"- {check.name}: **{check.status.value}** - {check.summary}"
            for check in self.checks
        )
        counter_lines = "\n".join(
            f"- {status.value}: {self.counters.get(status, 0)}"
            for status in CheckStatus
        )
        return (
            "# ARGUS REPORT\n\n"
            f"- Generated by: {self.generated_by}\n"
            f"- Guardian version: {self.guardian_version}\n"
            f"- Created at: {self.created_at.isoformat()}\n"
            f"- Overall: **{self.overall_status.value}**\n\n"
            f"## Summary\n\n{self.summary}\n\n"
            f"## Counters\n\n{counter_lines}\n\n"
            f"## Checks\n\n{check_lines}"
        )

    def to_json(self) -> str:
        """Return a deterministic JSON representation of the report."""
        payload = {
            "created_at": self.created_at.isoformat(),
            "guardian_version": self.guardian_version,
            "overall_status": self.overall_status.value,
            "checks": [
                {
                    "id": check.id,
                    "name": check.name,
                    "severity": check.severity.value,
                    "status": check.status.value,
                    "summary": check.summary,
                    "details": _json_value(check.details),
                    "checked_at": check.checked_at.isoformat(),
                    "duration_seconds": check.duration_seconds,
                }
                for check in self.checks
            ],
            "counters": {
                status.value: self.counters.get(status, 0)
                for status in CheckStatus
            },
            "summary": self.summary,
            "generated_by": self.generated_by,
        }
        return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _redact_text(value: str) -> str:
    return _SENSITIVE_TEXT_PATTERN.sub(lambda match: f"{match.group(1)}={_REDACTED}", value)


def _protect_mapping(value: Mapping[str, Any]) -> Mapping[str, Any]:
    protected: dict[str, Any] = {}
    for key, item in value.items():
        if not isinstance(key, str):
            msg = "details keys must be strings."
            raise ValueError(msg)
        normalized_key = key.lower().replace("-", "_")
        if _is_sensitive_key(normalized_key):
            protected[key] = _REDACTED
        else:
            protected[key] = _protect_value(item)
    return MappingProxyType(protected)


def _is_sensitive_key(normalized_key: str) -> bool:
    return normalized_key in _SENSITIVE_KEYS or normalized_key.endswith(
        ("_api_key", "_password", "_secret", "_token"),
    )


def _protect_value(value: Any) -> Any:
    if isinstance(value, Mapping):
        return _protect_mapping(value)
    if isinstance(value, (list, tuple, set, frozenset)):
        return tuple(_protect_value(item) for item in value)
    if isinstance(value, str):
        return _redact_text(value)
    return value


def _json_value(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _json_value(item) for key, item in value.items()}
    if isinstance(value, tuple):
        return [_json_value(item) for item in value]
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, Enum):
        return value.value
    return value
