"""Models for the Vox voice agent."""

from dataclasses import dataclass


@dataclass
class VoiceProfile:
    """Structured voice profile for narrated video production."""

    language: str
    voice_character: str
    speaking_style: str
    emotional_tone: str
    pace_words_per_minute: int
    pitch: str
    emphasis_notes: str
    pronunciation_notes: str
    multilingual_notes: str
    platform_fit: str
    summary: str
    generated_by: str

    def __post_init__(self) -> None:
        """Validate voice profile values."""
        string_fields = {
            "language": self.language,
            "voice_character": self.voice_character,
            "speaking_style": self.speaking_style,
            "emotional_tone": self.emotional_tone,
            "pitch": self.pitch,
            "emphasis_notes": self.emphasis_notes,
            "pronunciation_notes": self.pronunciation_notes,
            "multilingual_notes": self.multilingual_notes,
            "platform_fit": self.platform_fit,
            "summary": self.summary,
            "generated_by": self.generated_by,
        }
        for field_name, value in string_fields.items():
            if not value.strip():
                msg = f"{field_name} must not be empty."
                raise ValueError(msg)

        if self.pace_words_per_minute <= 0:
            msg = "pace_words_per_minute must be greater than 0."
            raise ValueError(msg)

    def to_markdown(self) -> str:
        """Return the voice profile as Markdown."""
        return (
            "# Voice Profile\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Language\n\n{self.language}\n\n"
            f"## Voice Character\n\n{self.voice_character}\n\n"
            f"## Speaking Style\n\n{self.speaking_style}\n\n"
            f"## Emotional Tone\n\n{self.emotional_tone}\n\n"
            f"## Pace\n\n{self.pace_words_per_minute} words per minute\n\n"
            f"## Pitch\n\n{self.pitch}\n\n"
            f"## Emphasis Notes\n\n{self.emphasis_notes}\n\n"
            f"## Pronunciation Notes\n\n{self.pronunciation_notes}\n\n"
            f"## Multilingual Notes\n\n{self.multilingual_notes}\n\n"
            f"## Platform Fit\n\n{self.platform_fit}\n\n"
            f"## Summary\n\n{self.summary}"
        )
