"""Models for the Mentor learning agent."""

from dataclasses import dataclass


@dataclass
class LearningInsight:
    """A structured learning derived from content performance."""

    category: str
    observation: str
    evidence: str
    recommendation: str
    confidence: float

    def __post_init__(self) -> None:
        """Validate learning insight values."""
        string_fields = {
            "category": self.category,
            "observation": self.observation,
            "evidence": self.evidence,
            "recommendation": self.recommendation,
        }
        for field_name, value in string_fields.items():
            if not value.strip():
                msg = f"{field_name} must not be empty."
                raise ValueError(msg)

        if not 0.0 <= self.confidence <= 1.0:
            msg = "confidence must be between 0.0 and 1.0."
            raise ValueError(msg)


@dataclass
class LearningReport:
    """Structured learning report generated from analytics."""

    video_id: str
    performance_summary: str
    strengths: list[LearningInsight]
    weaknesses: list[LearningInsight]
    experiments: list[str]
    recommended_actions: list[str]
    generated_by: str

    def __post_init__(self) -> None:
        """Validate learning report values."""
        if not self.strengths and not self.weaknesses:
            msg = "learning report must contain at least one strength or weakness."
            raise ValueError(msg)

        if not self.experiments:
            msg = "experiments must not be empty."
            raise ValueError(msg)

        if not self.recommended_actions:
            msg = "recommended_actions must not be empty."
            raise ValueError(msg)

    def to_markdown(self) -> str:
        """Return the learning report as Markdown."""
        strengths = "\n".join(
            (
                f"- {insight.category}: {insight.observation} "
                f"(confidence: {insight.confidence})"
            )
            for insight in self.strengths
        )
        weaknesses = "\n".join(
            (
                f"- {insight.category}: {insight.observation} "
                f"(confidence: {insight.confidence})"
            )
            for insight in self.weaknesses
        )
        experiments = "\n".join(f"- {experiment}" for experiment in self.experiments)
        actions = "\n".join(f"- {action}" for action in self.recommended_actions)
        return (
            f"# Learning Report: {self.video_id}\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Performance Summary\n\n{self.performance_summary}\n\n"
            f"## Strengths\n\n{strengths}\n\n"
            f"## Weaknesses\n\n{weaknesses}\n\n"
            f"## Experiments\n\n{experiments}\n\n"
            f"## Recommended Actions\n\n{actions}"
        )
