"""Models for the Athena business intelligence agent."""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum


class BusinessRiskSeverity(StrEnum):
    """Severity levels for business risks."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


@dataclass
class BusinessKPI:
    """A management-level business KPI."""

    name: str
    value: str
    description: str

    def __post_init__(self) -> None:
        """Validate KPI values."""
        for field_name, value in {
            "name": self.name,
            "value": self.value,
            "description": self.description,
        }.items():
            if not value.strip():
                msg = f"{field_name} must not be empty."
                raise ValueError(msg)


@dataclass
class BusinessOpportunity:
    """A management-level opportunity."""

    title: str
    probability: float
    impact: str
    recommendation: str

    def __post_init__(self) -> None:
        """Validate opportunity values."""
        if not 0.0 <= self.probability <= 1.0:
            msg = "probability must be between 0.0 and 1.0."
            raise ValueError(msg)


@dataclass
class BusinessRisk:
    """A management-level business risk."""

    title: str
    severity: BusinessRiskSeverity
    mitigation: str


@dataclass
class BusinessIntelligenceReport:
    """Executive business intelligence report for the CEO."""

    kpis: list[BusinessKPI]
    opportunities: list[BusinessOpportunity]
    risks: list[BusinessRisk]
    priorities: list[str]
    executive_summary: str
    generated_by: str
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def __post_init__(self) -> None:
        """Validate report values."""
        if not self.kpis:
            msg = "kpis must contain at least one BusinessKPI."
            raise ValueError(msg)

        if not self.opportunities:
            msg = "opportunities must contain at least one BusinessOpportunity."
            raise ValueError(msg)

        if not self.risks:
            msg = "risks must contain at least one BusinessRisk."
            raise ValueError(msg)

        if not self.priorities:
            msg = "priorities must contain at least one priority."
            raise ValueError(msg)

    def to_markdown(self) -> str:
        """Return the business intelligence report as Markdown."""
        kpis = "\n".join(
            f"- {kpi.name}: {kpi.value} ({kpi.description})" for kpi in self.kpis
        )
        opportunities = "\n".join(
            (
                f"- {opportunity.title}: {opportunity.probability} probability, "
                f"{opportunity.impact}"
            )
            for opportunity in self.opportunities
        )
        risks = "\n".join(
            f"- {risk.title}: {risk.severity.value} ({risk.mitigation})"
            for risk in self.risks
        )
        priorities = "\n".join(f"- {priority}" for priority in self.priorities)
        return (
            "# Business Intelligence Report\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Executive Summary\n\n{self.executive_summary}\n\n"
            f"## KPIs\n\n{kpis}\n\n"
            f"## Opportunities\n\n{opportunities}\n\n"
            f"## Risks\n\n{risks}\n\n"
            f"## Priorities\n\n{priorities}"
        )
