"""Models for the Aether creative director agent."""

from dataclasses import dataclass


@dataclass
class CreativeBrief:
    """Creative production brief for a video asset."""

    visual_style: str
    color_palette: str
    typography: str
    camera_style: str
    lighting_style: str
    animation_style: str
    avatar_style: str
    editing_style: str
    music_style: str
    emotional_tone: str
    platform_style: str
    branding_notes: str
    summary: str
    generated_by: str

    def to_markdown(self) -> str:
        """Return the creative brief as Markdown."""
        return (
            "# Creative Brief\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Visual Style\n\n{self.visual_style}\n\n"
            f"## Color Palette\n\n{self.color_palette}\n\n"
            f"## Typography\n\n{self.typography}\n\n"
            f"## Camera Style\n\n{self.camera_style}\n\n"
            f"## Lighting Style\n\n{self.lighting_style}\n\n"
            f"## Animation Style\n\n{self.animation_style}\n\n"
            f"## Avatar Style\n\n{self.avatar_style}\n\n"
            f"## Editing Style\n\n{self.editing_style}\n\n"
            f"## Music Style\n\n{self.music_style}\n\n"
            f"## Emotional Tone\n\n{self.emotional_tone}\n\n"
            f"## Platform Style\n\n{self.platform_style}\n\n"
            f"## Branding Notes\n\n{self.branding_notes}\n\n"
            f"## Summary\n\n{self.summary}"
        )
