"""Models for the Pulse music and sound agent."""

from dataclasses import dataclass


@dataclass
class MusicProfile:
    """Structured music and sound profile for short-form videos."""

    genre: str
    mood: str
    energy_level: str
    tempo_bpm: int
    transition_style: str
    sound_effect_style: str
    intro_style: str
    outro_style: str
    platform_fit: str
    copyright_strategy: str
    summary: str
    generated_by: str

    def __post_init__(self) -> None:
        """Validate music profile values."""
        string_fields = {
            "genre": self.genre,
            "mood": self.mood,
            "energy_level": self.energy_level,
            "transition_style": self.transition_style,
            "sound_effect_style": self.sound_effect_style,
            "intro_style": self.intro_style,
            "outro_style": self.outro_style,
            "platform_fit": self.platform_fit,
            "copyright_strategy": self.copyright_strategy,
            "summary": self.summary,
            "generated_by": self.generated_by,
        }
        for field_name, value in string_fields.items():
            if not value.strip():
                msg = f"{field_name} must not be empty."
                raise ValueError(msg)

        if self.tempo_bpm <= 0:
            msg = "tempo_bpm must be greater than 0."
            raise ValueError(msg)

    def to_markdown(self) -> str:
        """Return the music profile as Markdown."""
        return (
            "# Music Profile\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Genre\n\n{self.genre}\n\n"
            f"## Mood\n\n{self.mood}\n\n"
            f"## Energy Level\n\n{self.energy_level}\n\n"
            f"## Tempo\n\n{self.tempo_bpm} BPM\n\n"
            f"## Transition Style\n\n{self.transition_style}\n\n"
            f"## Sound Effect Style\n\n{self.sound_effect_style}\n\n"
            f"## Intro Style\n\n{self.intro_style}\n\n"
            f"## Outro Style\n\n{self.outro_style}\n\n"
            f"## Platform Fit\n\n{self.platform_fit}\n\n"
            f"## Copyright Strategy\n\n{self.copyright_strategy}\n\n"
            f"## Summary\n\n{self.summary}"
        )
