"""Models for the Apollo hook agent."""

from dataclasses import dataclass


@dataclass
class HookCandidate:
    """A scored hook candidate."""

    text: str
    score: float
    reason: str

    def __post_init__(self) -> None:
        """Validate hook candidate values."""
        if not 0.0 <= self.score <= 1.0:
            msg = "score must be between 0.0 and 1.0."
            raise ValueError(msg)


@dataclass
class OptimizedHook:
    """Optimized hook result selected from candidates."""

    original_hook: str
    selected_hook: HookCandidate
    candidates: list[HookCandidate]
    summary: str
    generated_by: str

    def to_markdown(self) -> str:
        """Return the optimized hook as Markdown."""
        candidate_lines = "\n".join(
            (
                f"- {candidate.text} "
                f"(score: {candidate.score}, reason: {candidate.reason})"
            )
            for candidate in self.candidates
        )
        return (
            "# Optimized Hook\n\n"
            f"Generated by: {self.generated_by}\n\n"
            f"## Original Hook\n\n{self.original_hook}\n\n"
            f"## Selected Hook\n\n{self.selected_hook.text}\n\n"
            f"Score: {self.selected_hook.score}\n\n"
            f"Reason: {self.selected_hook.reason}\n\n"
            f"## Candidates\n\n{candidate_lines}\n\n"
            f"## Summary\n\n{self.summary}"
        )
