"""Run Atlas locally and write a trend report to an Obsidian vault."""

import os
import sys
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence

from agents.trend_research.agent import TrendResearchAgent
from agents.trend_research.report import TrendReport
from engine.runtime.capability import AgentCapability
from engine.runtime.runtime import HeliosRuntime
from engine.tasks.priority import TaskPriority
from engine.tasks.status import TaskStatus
from engine.tasks.task import Task
from integrations.obsidian.store import ObsidianMemoryStore


VAULT_ENV_VAR = "HELIOS_OBSIDIAN_VAULT"


@dataclass(frozen=True)
class AtlasDemoResult:
    """Result data printed by the local Atlas demo runner."""

    task_id: str
    status: TaskStatus
    query: str
    trend_count: int
    generated_by: str
    markdown_path: Path


def parse_query(args: Sequence[str]) -> str:
    """Return the query from command-line arguments."""
    if not args or not args[0].strip():
        msg = (
            'Bitte eine Query angeben, z. B. '
            'uv run python scripts/run_atlas_demo.py "AI Agents"'
        )
        raise ValueError(msg)

    return args[0].strip()


def get_vault_path(env: Mapping[str, str] = os.environ) -> Path:
    """Return the Obsidian vault path from the environment."""
    raw_vault_path = env.get(VAULT_ENV_VAR, "").strip()
    if not raw_vault_path:
        msg = (
            f"{VAULT_ENV_VAR} ist nicht gesetzt. "
            'Beispiel: export HELIOS_OBSIDIAN_VAULT="/vollständiger/pfad/zum/vault"'
        )
        raise RuntimeError(msg)

    return Path(raw_vault_path).expanduser()


def create_demo_task(query: str) -> Task:
    """Create a trend research task for the Atlas demo."""
    return Task(
        task_id=f"atlas-demo-{uuid.uuid4().hex}",
        title="Atlas Demo Trend Research",
        description="Run Atlas against mock trend and mock LLM tools.",
        priority=TaskPriority.MEDIUM,
        required_capability=AgentCapability.TREND_RESEARCH,
        payload={"query": query},
    )


def run_demo(query: str, vault_path: Path) -> AtlasDemoResult:
    """Run Atlas through HeliosRuntime and return printable result data."""
    memory_store = ObsidianMemoryStore(vault_path)
    runtime = HeliosRuntime()
    atlas = TrendResearchAgent(memory_store=memory_store)
    task = create_demo_task(query)

    runtime.register(atlas)
    runtime.start()
    report = runtime.submit_task(task)

    if not isinstance(report, TrendReport):
        msg = "Atlas did not return a TrendReport."
        raise RuntimeError(msg)

    markdown_path = vault_path / f"trend-report-{task.task_id}.md"
    return AtlasDemoResult(
        task_id=task.task_id,
        status=task.status,
        query=query,
        trend_count=len(report.trends),
        generated_by=report.generated_by,
        markdown_path=markdown_path.resolve(),
    )


def format_result(result: AtlasDemoResult) -> str:
    """Format a successful demo result for terminal output."""
    return "\n".join(
        [
            f"Task-ID: {result.task_id}",
            f"Status: {result.status.value}",
            f"Query: {result.query}",
            f"Anzahl Trends: {result.trend_count}",
            f"Generated By: {result.generated_by}",
            f"Markdown-Datei: {result.markdown_path}",
        ],
    )


def main(argv: Sequence[str] | None = None) -> int:
    """Run the Atlas demo from the command line."""
    args = sys.argv[1:] if argv is None else argv
    try:
        query = parse_query(args)
        vault_path = get_vault_path()
        result = run_demo(query, vault_path)
    except Exception as error:
        print(f"Fehler: {error}", file=sys.stderr)
        return 1

    print(format_result(result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
